development:
  adapter: postgresql
  database: adopt_a_thing_development
  host: localhost

test:
  adapter: postgresql
  database: adopt_a_thing_test
  host: localhost

production:
 adapter: postgresql
 database: adopt_a_thing_prod
 host: localhost
